
// 1
//váriaveis opcionais são variáveis que podem conter um valor ou não. Ultilizamos para situações das quais não sabemos se o tipo de valor que vamos receber, ou se vamos receber algum valor

//2
//var arraylist = [3,4]

//var otherSet = Set<Double>(arrayLiteral: 4.9, 2.1, 7.8)

//var dicionario = Dictionary<String, Int>()
//dicionario["joalheiro"] = 65
//dicionario["Chaleira"] = 40
//dicionario["Ametista"] = 12
//dicionario["Abajour"] = 78

//print(arraylist)

//print(otherSet)

//print(dicionario)

//3
// O set apresenta os valores de forma aleatória, Array os apresenta em ordem.

//4
//var arraylist = [1, 13, 26, 38, 39, 41, 50, 74, 80, 90, 100]


//5
//let soma = array2.reduce(0, +)

//print(soma)
